name: dimamba
type: dimamba
hidden_size: 256
cond_dim: 128
length: 32768
n_blocks: 8
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False
bidirectional: True,
bidirectional_strategy: add
bidirectional_weight_tie: True
